### ISSUE TITLE
How to use this with 2018.4 version of unity.

### ISSUE THREAD

**Issue by midopooler** [daniellochner/Simple-Scroll-Snap#1]
I cannot download this asset from the asset store. Also I can't afford to upgrade my unity version due to some other compatibility issue. So any way through which I can use this in my 2018.4 project? @daniellochner

**Comment by daniellochner** [comment]
Hi there,

I've exported the asset as a "Unity Package".

To import this into your project, first extract the attached zip file and then navigate to "Assets > Import Package > Custom Package" and select the contained .unityPackage.

Hope this helps!

[Simple Scroll-Snap.zip](https://github.com/daniellochner/Simple-Scroll-Snap/files/5078645/Simple.Scroll-Snap.zip)

**Comment by midopooler** [comment]
Much thanks for the reply. I knew the package method. Just wanted to confirm that there isn't anything which can't performed in 2018 version.

**Comment by midopooler** [comment]
It did work well. Thanks,
Just a quick query, I want my viewport content to skip from 5 to 1 and from 1 to 5. I went to the code but couldn't find that particular array/list. please help me out?
