### ISSUE TITLE
Android only bug when adding panels to disabled object

### ISSUE THREAD

**Issue by Brainzy** [daniellochner/Simple-Scroll-Snap#10]
As title says, you get a null error only on android. Happens with all add methods Add(), AddToBack() , AddToFront(). Work around is to enable panels when adding and then disable.

**Comment by daniellochner** [comment]
Hi there! Thanks for letting me know about this. The issue has now been [resolved](https://github.com/daniellochner/Simple-Scroll-Snap/commit/c440b983f4c96903f114f46f2eae268467596014).
