### ISSUE TITLE
Go to Panel without Scroll Animation

### ISSUE THREAD

**Issue by kenofori** [daniellochner/Simple-Scroll-Snap#6]
Hi there,

We have Go to Panel which uses scroll animation, but there are cases when we have to show same scroll snap again from first panel immediatly instead of scroll animation , so how can we achieve that?

Thanks

**Comment by daniellochner** [comment]
Hi there! To set the starting panel, you can adjust the `Starting Panel` range slider in your Scroll-Snap's inspector window!
