### ISSUE TITLE
CurrentPanel weird behavior

### ISSUE THREAD

**Issue by smanganaro** [daniellochner/Simple-Scroll-Snap#8]
Hi there,

I might be wrong, but I think I found a strange behavior in the code, or at least one not intuitive.

I'm using a version of the Example 1 you provide, and on my proyect, I need to know on which panel/element I'm standing so I can render some other stuff. In other words, if CurrentPanel = 0, then I render MyComponent[0], and so on.

So what I do is to access CurrentPanel variable value. I would expect this variable to start on 0; if I move right or down, increase it's value by 1; if I move left or up, decrease it's value by 1 (if I'm on 0, and InfiniteScrolling is active, then maxValue).

The issue is the following: After the first movement, the CurrentPanel value stays on 0, independantly of the direction you move. That means everything is shifted.

Another example: Let's say you are snaping on a direction (for instance, right) and CurrentPanel is increasing it's value, whenever you change to the opposite direction (in this case left), on the first movement, CurrentPanel still increases it's value before start decreasing it.

On this movements: Start->Right->Right->Left I would expect 0->1->2->1, and I get 0->0->1->2

I replicated it with your Example1 as well by adding to Previous and Next Buttons a function that prints CurrentValue. I think this happens with TargetPanel too, but I didn't test that much.

I hope you can help me with this. If it's a bug, by fixing it, and if I'm wrong, by clarifying things to me.

Thank you for your time, have a nice day.

**Comment by smanganaro** [comment]
Update: I think the OnPanelSelecting eventHandler might be related, since I tried using it and didn't trigger on those cases. 

I had to implement those functionalities by myself as a quick fix, cause I didn't want to mess up anything in your code. 

I did this: 
              
     public int CurrentPanel = 0;
     public SimpleScrollSnap ScrollSnap;
     public ItemDescriptionHandler itemDescriptionHandler; **_//custom class that updates another UI object_**

     private void Update(){
 
                   _**//for movement**_
                   Vector2 directionalInput = new Vector2(Input.GetAxisRaw("Horizontal"), Input.GetAxisRaw("Vertical"));

                    if (directionalInput.y > 0.5){
                          if (CurrentPanel == 0) {
                                   CurrentPanel = ScrollSnap.NumberOfPanels - 1;
                          } else {
                                   CurrentPanel--;
                          }
                          ScrollSnap.GoToNextPanel();

                   }else if (directionalInput.y < -0.5){
                          if (CurrentPanel == ScrollSnap.NumberOfPanels - 1){
                                  CurrentPanel = 0;
                          } else {
                                  CurrentPanel++;
                          }
                           ScrollSnap.GoToPreviousPanel();
                   }

                   itemDescriptionHandler.UpdateDescription();   }

**Comment by daniellochner** [comment]
Hi there! Everything sounds like it was working as expected, however, the properties were just poorly named! I've released a new version of the asset in I've addressed these issues:
- Firstly, all events are now parameterized, and so you should use them where possible.
- Next, I renamed `TargetPanel` and `OnPanelSelected` to `SelectedPanel` and `OnPanelSelected` as well as `CurrentPanel` and `OnPanelChanged` to `CenteredPanel` and `OnPanelCentered` respectively. This should more accurately illustrate their purposes!
- Finally, `OnPanelSelecting` and `OnPanelChanging` have been removed, since they weren't useful.

Hope this helps!
